---
- hosts:
  - web
  - jenkins
  become: yes
  vars:
    conf_path: '/etc/ssh/sshd_config'

  tasks:
    - name: modify sshd_config
      replace:
        dest={{ conf_path }}
        regexp='^PasswordAuthentication yes'
        replace='PasswordAuthentication no'
      notify: restart sshd                
  handlers:
    - name: restart sshd
      systemd:
         state: restarted
         name: sshd.service
